config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  get "generos/index"
  get "generos/show"
  get "generos/new"
  get "generos/create"
  get "generos/edit"
  get "generos/update"
  get "generos/destroy"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  resources :users, only: [ :new, :create ]


  resources :filmes do
    resources :comentarios
  end
  root "filmes#index"

  resources :comentarios, only: [ :create, :destroy ]

  resources :generos


  get '/run_migrations', to: 'migrations#run'


end

app/models/genero.rb
class Genero < ApplicationRecord
  has_and_belongs_to_many :filmes
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_genero, only: [ :show, :edit, :new, :update, :destroy ]
  def index
    @generos = Genero.all
  end

  def show
    @filmes = @genero.filmes
  end


  def new
    @genero = Genero.new
  end


  def create
    @genero = Genero.new(genero_params)
    if @genero.save
      redirect_to Genero, notice: "Gênero criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end


  def update
    if @genero.update(genero_params)
      redirect_to Genero, notice: "Gênero atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genero.destroy
    redirect_to generos_path, notice: "Gênero excluído com sucesso."
  end

  private

  def set_genero
    @genero = Genero.find(params[:id])
  end

  def genero_params
    params.require(:genero).permit(:nome)
  end
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/generos/edit.html.erb
<h1>Editar Gênero</h1>

<%= form_with(model: @genero) do |form| %>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Atualizar", class: "button is-primary" %>
  </div>
<% end %>

app/views/generos/index.html.erb
<h2 class="title is-2">Gêneros</h2>
<%= link_to "Novo Gênero", new_genero_path, class: "button is-success" %>
<br>
<br>
<% @generos.each do |genero| %>
    <br>
    <%= link_to genero.nome, genero_path(genero), class: "tag is-link" %>
    <%= link_to "Editar", edit_genero_path(genero) %> |
    <%= link_to "Excluir", genero, data: { turbo_method: :delete, confirm: "Tem certeza?" } %>
    <br>
<% end %>

app/views/generos/new.html.erb
<h1>Novo Gênero</h1>

<%= form_with(model: @genero) do |form| %>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class: "button is-primary" %>
  </div>
<% end %>

app/views/generos/show.html.erb
<div class="columns is-multiline">
  <% @filmes.each do |filme| %>
    <div class="column is-6">
      <div class="card" style="display:flex; flex-direction:column; height:100%;">
        
        <div class="card-image">
          <figure class="image is-4by3">
            <% if filme.capa.attached? %>
              <%= image_tag filme.capa, style: "object-fit: cover; width: 100%; height: 100%;" %>
            <% else %>
            
              <img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Placeholder" style="object-fit: cover; width: 100%; height: 100%;">
            <% end %>
          </figure>
        </div>

        <!-- Conteúdo do card -->
        <div class="card-content" style="flex-grow:1;">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <a href="<%= filme_path(filme) %>"><%= filme.titulo %></a>
              </p>
              <p class="subtitle is-6">Postado por: <%= filme.user.email_address %></p>
            </div>
          </div>

          <div class="content">
            <%= filme.sinopse %>
            <br>
            <time datetime="<%= filme.created_at.iso8601 %>">
              Postado em: <%= filme.created_at.strftime("%d/%m/%Y %H:%M") %>
            </time>
          </div>
        </div>

        <!-- Footer com ações -->
        <% if authenticated? && filme.user == Current.user %>
          <footer class="card-footer">
            <a href="<%= edit_filme_path(filme) %>" class="card-footer-item">Editar</a>
            <a class="card-footer-item"> <%= button_to "Deletar", filme, method: :delete, data: { turbo_confirm: "Are you sure?" } %></a>
          </footer>
        <% end %>

      </div>
    </div>
  <% end %>
</div>