config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  get "generos/index"
  get "generos/show"
  get "generos/new"
  get "generos/create"
  get "generos/edit"
  get "generos/update"
  get "generos/destroy"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  resources :users, only: [ :new, :create ]


  resources :filmes do
    resources :comentarios
  end
  root "filmes#index"

  resources :comentarios, only: [ :create, :destroy ]

  resources :generos


  get '/run_migrations', to: 'migrations#run'


end

app/models/filme.rb
class Filme < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy

  has_and_belongs_to_many :generos

  has_one_attached :capa

  validates :titulo, presence: true
  validates :sinopse, presence: true
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: [ :show, :edit, :update, :destroy ]
  allow_unauthenticated_access only: %i[ index show ]


  def index
    @filmes = Filme.all

    if params[:titulo].present?
      @filmes = @filmes.where("titulo ILIKE ?", "%#{params[:titulo]}%")
    end

    if params[:diretor].present?
      @filmes = @filmes.where("diretor ILIKE ?", "%#{params[:diretor]}%")
    end

    if params[:data_postagem].present?
      @filmes = @filmes.where("DATE(lancamento) = ?", params[:lancamento])
    end

    @filmes = @filmes.order(created_at: :desc).page(params[:page]).per(6)
  end


  def show
    @comentarios = @filme.comentarios.order(created_at: :desc)
    @comentario = Comentario.new
  end

  def new
    @filme = Filme.new
    @generos = Genero.all
  end

  def create
    @filme = Current.user.filmes.new(filme_params)
    if @filme.save
      redirect_to @filme
    else
      @generos = Genero.all
      render :new
    end
  end

  def update
    if @filme.update(filme_params)
      redirect_to @filme
    else
      @generos = Genero.all
      render :edit
    end
  end

  def edit
    @generos = Genero.all
  end


  def destroy
    @filme.destroy
    redirect_to filmes_path
  end

  private
    def set_filme
      @filme = Filme.find(params[:id])
    end

    def filme_params
      params.require(:filme).permit(
        :titulo,
        :sinopse,
        :diretor,
        :lancamento,
        :duracao,
        :capa,                # caso queira permitir upload da capa
        genero_ids: []        # array de IDs para a relação N:N com gêneros
      )
    end
end

app/views/filmes/_form.html.erb
<%= form_with model: filme do |form| %>
    <% if form.object.errors.any? %>
        <p class="error"><%= form.object.errors.full_messages.first %></p>
    <% end %>

    <div>
        <%= form.label :titulo %>
        <%= form.text_field :titulo %>
        <br>
        <%= form.label :sinopse %>
        <%= form.text_field :sinopse %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/filmes/edit.html.erb
<h1 class="title is-1">Editar Filme</h1>

<%= form_with(model: @filme) do |form| %>
  <div>
    <%= form.label :titulo , class: "label"%>
    <%= form.text_field :titulo, class:"input" %>
  </div>

  <div>
    <%= form.label :sinopse, class: "label" %>
    <%= form.text_area :sinopse , class: "textarea", placeholder: "Escreva a sinopse do filme" %>
  </div>

  <div>
    <%= form.label :diretor, class: "label" %>
    <%= form.text_field :diretor, class: "input", placeholder: "Nome do diretor" %>
  </div>

  <div>
    <%= form.label :lancamento, "Data de Lançamento", class: "label" %>
    <%= form.date_field :lancamento, class: "input" %>
  </div>

  <div>
    <%= form.label :duracao, "Duração (minutos)", class: "label" %>
    <%= form.number_field :duracao, class: "input", min: 0 %>
  </div>

  <hr>

  <div>
    <%= form.label :generos, "Generos", class: "label" %>
    <% @generos.each do |genero| %>
      <div>
        <%= check_box_tag "filme[genero_ids][]", genero.id, @filme.generos.include?(genero), id: "filme_genero_#{genero.id}", class:"checkbox" %>
        <%= label_tag "filme_genero_#{genero.id}", genero.nome %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :capa, "Imagem de capa", class: "label" %>
    <%= form.file_field :capa %>
  </div>

  <hr>

  <div>
    <%= form.submit "Salvar", class: "button is-link" %>
    <%= button_to "Cancel", filmes_path,  class: "button"  %>
  </div>
<% end %>

app/views/filmes/index.html.erb
<h2 class="title is-2">Filmes mais recentes</h2>

<%= form_with url: filmes_path, method: :get, local: true do |form| %>
  <div class="field">
    <%= form.label :titulo, "Título" %>
    <%= form.text_field :titulo, value: params[:titulo], class: "input", placeholder: "Título do filme" %>
  </div>

  <div class="field">
    <%= form.label :diretor, "Diretor" %>
    <%= form.text_field :diretor, value: params[:diretor], class: "input", placeholder: "Nome do diretor" %>
  </div>

  <div class="field">
    <%= form.label :lancamento, "Data de lancamento" %>
    <%= form.date_field :lancamento, value: params[:lancamento], class: "input" %>
  </div>

  <div class="control">
    <%= form.submit "Buscar", class: "button is-info" %>
  </div>
<% end %>

<hr>




<% if authenticated? %>
  <%= link_to "Novo Filme", new_filme_path, class: "button is-link mb-4" %>
<% end %>

<div class="columns is-multiline">
  <% @filmes.each do |filme| %>
    <div class="column is-6">
      <div class="card" style="display:flex; flex-direction:column; height:100%;">
        
        <div class="card-image">
          <figure class="image is-4by3">
            <% if filme.capa.attached? %>
              <%= image_tag filme.capa, style: "object-fit: cover; width: 100%; height: 100%;" %>
            <% else %>
            
              <img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Placeholder" style="object-fit: cover; width: 100%; height: 100%;">
            <% end %>
          </figure>
        </div>

        <!-- Conteúdo do card -->
        <div class="card-content" style="flex-grow:1;">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <a href="<%= filme_path(filme) %>"><%= filme.titulo %></a>
              </p>
              <p class="subtitle is-6">Postado por: <%= filme.user.email_address %></p>
            </div>
          </div>

          <div class="content">
            <%= filme.sinopse %>
            <br>
            <time datetime="<%= filme.created_at.iso8601 %>">
              Postado em: <%= filme.created_at.strftime("%d/%m/%Y %H:%M") %>
            </time>
          </div>
        </div>

        <!-- Footer com ações -->
        <% if authenticated? && filme.user == Current.user %>
          <footer class="card-footer">
            <a href="<%= edit_filme_path(filme) %>" class="card-footer-item">Editar</a>
            <a class="card-footer-item"> <%= button_to "Deletar", filme, method: :delete, data: { turbo_confirm: "Are you sure?" } %></a>
          </footer>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

<!-- Paginação -->
<div class="mt-4">
  <%= paginate @filmes %>
</div>

app/views/filmes/new.html.erb
<h1 class="title is-1">Novo Filme</h1>

<%= form_with(model: @filme) do |form| %>
  <div>
    <%= form.label :titulo , class: "label"%>
    <%= form.text_field :titulo, class:"input" %>
  </div>

  <div>
    <%= form.label :sinopse, class: "label" %>
    <%= form.text_area :sinopse , class: "textarea", placeholder: "Escreva a sinopse do filme" %>
  </div>

  <div>
    <%= form.label :diretor, class: "label" %>
    <%= form.text_field :diretor, class: "input", placeholder: "Nome do diretor" %>
  </div>

  <div>
    <%= form.label :lancamento, "Data de Lançamento", class: "label" %>
    <%= form.date_field :lancamento, class: "input" %>
  </div>

  <div>
    <%= form.label :duracao, "Duração (minutos)", class: "label" %>
    <%= form.number_field :duracao, class: "input", min: 0 %>
  </div>

  <hr>

  <div>
    <%= form.label :generos, "Generos", class: "label" %>
    <% @generos.each do |genero| %>
      <div>
        <%= check_box_tag "filme[genero_ids][]", genero.id, @filme.generos.include?(genero), id: "filme_genero_#{genero.id}", class:"checkbox" %>
        <%= label_tag "filme_genero_#{genero.id}", genero.nome %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :capa, "Imagem de capa", class: "label" %>
    <%= form.file_field :capa %>
  </div>

  <hr>

  <div>
    <%= form.submit "Salvar", class: "button is-link" %>
    <%= button_to "Cancel", filmes_path,  class: "button"  %>
  </div>
<% end %>

app/views/filmes/show.html.erb
<div>
    <%= link_to "Back", filmes_path %>
    <div class="card">
        <div class="card-image">
            <figure class="image is-4by3">
            <% if @filme.capa.attached? %>
              <%= image_tag @filme.capa, style: "object-fit: cover; width: 100%; height: 100%;" %>
            <% else %>
            
              <img src="https://bulma.io/assets/images/placeholders/1280x960.png" alt="Placeholder" style="object-fit: cover; width: 100%; height: 100%;">
            <% end %>
          </figure>
        </div>
        <div class="card-content">
            <div class="media">
                <div class="media-content">
                    <p class="title is-4"><%= @filme.titulo %></p>
                    <p class="subtitle is-6">Postado por: <%= @filme.user.email_address %></p>
                </div>
            </div>

            <div class="content">
                <%= @filme.sinopse %>
                <br />
                <time datetime="2016-1-1">Postado em: <%= @filme.user.created_at %></time>
            </div>
        </div>
        <% if authenticated? and @filme.user == Current.user %>
            <footer class="card-footer">
                <a href="<%=edit_filme_path(@filme)%>" class="card-footer-item" >Editar</a>
                <a class="card-footer-item"> <%= button_to "Deletar", @filme, method: :delete, data: { turbo_confirm: "Are you sure?" } %></a>
            </footer>
        <% end %>

    </div>
    <p><h5 class="title is-5">Gêneros: </h5> <%= @filme.generos.pluck(:nome).join(", ") %></p>
    <br>
    
    <h4 class="title is-4">Deixe um comentario: </h4>
    <%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
    <%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>
    <form action="<%= filme_comentarios_path(@filme) %>" method="post">
        <%= csrf_meta_tags %>
        <div>
            <textarea class="input" name="comentario[conteudo]" id="comentario_conteudo" rows="3" placeholder="Escreva algo..." style="width: 100%; min-width:100%;max-width:100%; height:80px; min-height:80px; max-height:80px;"></textarea>
        </div>
        <br>
        <div>
            <button class="button is-link" type="submit">Publicar</button>
        </div>
        <br>
    </form>
    <% if @comentarios.any? %>
        <h3 class="title is-3">Comentários:</h3>
        <% @comentarios.each do |comentario| %>
            <article class="message">
            <div class="message-header">
                <p><%= comentario.user.email_address %></p>

                <% if comentario.user == Current.user %>
                <%= button_to "Deletar", filme_comentario_path(@filme, comentario), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "button is-danger is-small" %>
                <% end %>

            </div>
            <div class="message-body">
                <%= comentario.conteudo %>
            </div>
            </article>
        <% end %>
    <% end %>

    
</div>