config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get "users/create"
  get "generos/index"
  get "generos/show"
  get "generos/new"
  get "generos/create"
  get "generos/edit"
  get "generos/update"
  get "generos/destroy"
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"


  resources :users, only: [ :new, :create ]


  resources :filmes do
    resources :comentarios
  end
  root "filmes#index"

  resources :comentarios, only: [ :create, :destroy ]

  resources :generos


  get '/run_migrations', to: 'migrations#run'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :user
  belongs_to :filme

  validates :conteudo, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/filme.rb
class Filme < ApplicationRecord
  belongs_to :user
  has_many :comentarios, dependent: :destroy

  has_and_belongs_to_many :generos

  has_one_attached :capa

  validates :titulo, presence: true
  validates :sinopse, presence: true
end

app/models/genero.rb
class Genero < ApplicationRecord
  has_and_belongs_to_many :filmes
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :filmes, dependent: :destroy
  has_many :comentarios, dependent: :destroy
  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def migrate
    if Rails.env.production?
      begin
        ActiveRecord::Migrator.migrate(Rails.application.paths['db/migrate'].to_a, nil)
        render plain: "Migrations rodadas com sucesso!"
      rescue => e
        render plain: "Erro: #{e.message}"
      end
    else
      render plain: "Apenas em produção"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: [ :show, :edit, :update, :destroy ]
  allow_unauthenticated_access only: %i[ index show ]


  def index
    @filmes = Filme.all

    if params[:titulo].present?
      @filmes = @filmes.where("titulo ILIKE ?", "%#{params[:titulo]}%")
    end

    if params[:diretor].present?
      @filmes = @filmes.where("diretor ILIKE ?", "%#{params[:diretor]}%")
    end

    if params[:data_postagem].present?
      @filmes = @filmes.where("DATE(lancamento) = ?", params[:lancamento])
    end

    @filmes = @filmes.order(created_at: :desc).page(params[:page]).per(6)
  end


  def show
    @comentarios = @filme.comentarios.order(created_at: :desc)
    @comentario = Comentario.new
  end

  def new
    @filme = Filme.new
    @generos = Genero.all
  end

  def create
    @filme = Current.user.filmes.new(filme_params)
    if @filme.save
      redirect_to @filme
    else
      @generos = Genero.all
      render :new
    end
  end

  def update
    if @filme.update(filme_params)
      redirect_to @filme
    else
      @generos = Genero.all
      render :edit
    end
  end

  def edit
    @generos = Genero.all
  end


  def destroy
    @filme.destroy
    redirect_to filmes_path
  end

  private
    def set_filme
      @filme = Filme.find(params[:id])
    end

    def filme_params
      params.require(:filme).permit(
        :titulo,
        :sinopse,
        :diretor,
        :lancamento,
        :duracao,
        :capa,                # caso queira permitir upload da capa
        genero_ids: []        # array de IDs para a relação N:N com gêneros
      )
    end
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_genero, only: [ :show, :edit, :new, :update, :destroy ]
  def index
    @generos = Genero.all
  end

  def show
    @filmes = @genero.filmes
  end


  def new
    @genero = Genero.new
  end


  def create
    @genero = Genero.new(genero_params)
    if @genero.save
      redirect_to Genero, notice: "Gênero criado com sucesso."
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end


  def update
    if @genero.update(genero_params)
      redirect_to Genero, notice: "Gênero atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genero.destroy
    redirect_to generos_path, notice: "Gênero excluído com sucesso."
  end

  private

  def set_genero
    @genero = Genero.find(params[:id])
  end

  def genero_params
    params.require(:genero).permit(:nome)
  end
end

app/controllers/migrations_controller.rb
class MigrationsController < ApplicationController
  def run
    if Rails.env.production?
      begin
        # Executa todas as migrations pendentes
        ActiveRecord::Base.connection
        ActiveRecord::MigrationContext.new("db/migrate").migrate
        render plain: "Migrations executadas com sucesso!"
      rescue => e
        render plain: "Erro ao rodar migrations: #{e.message}"
      end
    else
      render plain: "Somente produção"
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_password_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      @user.sessions.destroy_all
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_path, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to filmes_path
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to root_path, notice: "Cadastro realizado com sucesso!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Videolocadora" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Videolocadora">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">


        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="<%= root_path %>">
            Filmes
          </a>
          <a class="navbar-item" href="<%= generos_path %>">
            Gêneros
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% unless authenticated? %>
                <a class="button is-primary" href="<%= new_user_path %>">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light" href="<%= new_session_path %>">
                  Log in
                </a>
              <% else %>
                <%= Current.user.email_address %>
                <%= link_to "Log out", session_path,
                data: { turbo_method: :delete },
                class: "navbar-item button is-light"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div style="width: 50%; margin:0 auto;">
      <%= yield %>
    </div>
  </body>
</html>